// console.assert(5 < 4);
// console.clear();
// console.error("Que acabas de hacer");
// console.info("Hiciste muy bien tu trabajo, pero esto ya no se utiliza más");
// console.log("Hiciste muy bien tu trabajo, pero esto ya no se utiliza más");
// console.table([1, 2, 4, 5, 6, 3, 5, ]);
// console.info([1, 4, 54, 6, 35, 85]);
// console.dir([1, 4, 54, 6, 35, 85]);
// console.count();
// console.count();
// console.count();
// console.count();
// console.count();
// console.count();
// console.count();
// console.count();
// console.count();
// console.count();
// console.countReset();
// console.count();
// console.count();
// console.count();
console.log("%cHola", "color:red;background:black;padding:20px 100px;border:3px solid, blue" );